variables:
  GOPATH: ${CI_PROJECT_DIR}/go/.cache

stages: [test]

default:
  image: ${CI_REGISTRY}/adagioio/devops/docker-adagio-build-v2

test:
  stage: test
  script:
    - mkdir -p go/.cache
    - go install github.com/jstemmer/go-junit-report@v1.0.0
    - go test ./... -v -coverprofile=coverage.out -p 1 | tee /tmp/gotest.result
    - cat /tmp/gotest.result | ${GOPATH}/bin/go-junit-report -set-exit-code > report.xml
    - go tool cover -func=coverage.out
    - go tool cover -html=coverage.out -o coverage.html
  cache:
    paths:
      - ${GOPATH}/pkg/mod
  artifacts:
    paths:
      - coverage.html
    reports:
      junit: report.xml
